// ============================================================================
// AUTO-GENERATED by export_to_webapp.py — DO NOT EDIT MANUALLY
// Run: cd bazaario_analytics && python3 export_to_webapp.py
// Generated: 2026-03-26 19:22:44
// ============================================================================

// ---------------------------------------------------------------------------
// Vendor Analytics (VendorSalesAnalytics.tsx)
// ---------------------------------------------------------------------------

export const vendorSalesData = [
  {
    "id": 1,
    "date": "Mon",
    "sales": 645.71,
    "orders": 63
  },
  {
    "id": 2,
    "date": "Tue",
    "sales": 633.95,
    "orders": 64
  },
  {
    "id": 3,
    "date": "Wed",
    "sales": 527.32,
    "orders": 54
  },
  {
    "id": 4,
    "date": "Thu",
    "sales": 565.95,
    "orders": 54
  },
  {
    "id": 5,
    "date": "Fri",
    "sales": 480.79,
    "orders": 48
  },
  {
    "id": 6,
    "date": "Sat",
    "sales": 838.87,
    "orders": 61
  },
  {
    "id": 7,
    "date": "Sun",
    "sales": 773.46,
    "orders": 53
  }
];

export const vendorProductData = [
  {
    "name": "Lamb Satay (10pc)",
    "value": 1267.59,
    "count": 226
  },
  {
    "name": "Mixed Satay Platter",
    "value": 1163.28,
    "count": 119
  },
  {
    "name": "Chicken Satay (10pc)",
    "value": 1098.26,
    "count": 212
  },
  {
    "name": "Beef Satay (10pc)",
    "value": 854.15,
    "count": 130
  },
  {
    "name": "Satay Sauce & Ketupat",
    "value": 82.77,
    "count": 10
  }
];

export const vendorHourlyData = [
  {
    "id": 1,
    "hour": "6PM",
    "orders": 21
  },
  {
    "id": 2,
    "hour": "7PM",
    "orders": 55
  },
  {
    "id": 3,
    "hour": "8PM",
    "orders": 101
  },
  {
    "id": 4,
    "hour": "9PM",
    "orders": 121
  },
  {
    "id": 5,
    "hour": "10PM",
    "orders": 82
  },
  {
    "id": 6,
    "hour": "11PM",
    "orders": 17
  }
];

export const vendorStats = [
  {
    "label": "Total Revenue",
    "value": "$4,466.05",
    "change": "+12.5%",
    "positive": true
  },
  {
    "label": "Total Orders",
    "value": "397",
    "change": "+8.3%",
    "positive": true
  },
  {
    "label": "Avg Order Value",
    "value": "$11.25",
    "change": "-2.1%",
    "positive": false
  },
  {
    "label": "Customers",
    "value": "267",
    "change": "+15.2%",
    "positive": true
  }
];

export const vendorInsights = {
  "revenueGrowth": "+12.5%",
  "weekendLift": "40.3%",
  "totalOrders": 397,
  "repeatCustomerPct": "68%",
  "avgOrderValue": "$11.25",
  "peakHour": "9:00 PM - 10:00 PM",
  "peakOrders": 121,
  "slowHour": "11:00 PM - 12:00 PM"
};

// ---------------------------------------------------------------------------
// Admin Dashboard (AdminDashboard.tsx)
// ---------------------------------------------------------------------------

export const adminStats = {
  "totalRevenue": 137105.11,
  "totalEvents": 8,
  "totalVendors": 38,
  "activeEvents": 3,
  "totalOrders": 15000,
  "platformFees": 4113.15
};

export const adminRevenueData = [
  {
    "id": 1,
    "date": "Mon",
    "revenue": 17933.58
  },
  {
    "id": 2,
    "date": "Tue",
    "revenue": 17395.78
  },
  {
    "id": 3,
    "date": "Wed",
    "revenue": 16176.98
  },
  {
    "id": 4,
    "date": "Thu",
    "revenue": 18075.36
  },
  {
    "id": 5,
    "date": "Fri",
    "revenue": 17469.65
  },
  {
    "id": 6,
    "date": "Sat",
    "revenue": 25282.39
  },
  {
    "id": 7,
    "date": "Sun",
    "revenue": 24771.37
  }
];

export const adminEventData = [
  {
    "name": "Toa Payoh",
    "vendors": 38,
    "revenue": 17618.81
  },
  {
    "name": "Jurong East",
    "vendors": 38,
    "revenue": 17527.46
  },
  {
    "name": "Clementi Bazaar",
    "vendors": 38,
    "revenue": 17139.62
  },
  {
    "name": "Bedok",
    "vendors": 38,
    "revenue": 17106.21
  },
  {
    "name": "Woodlands",
    "vendors": 38,
    "revenue": 17082.02
  },
  {
    "name": "Ang Mo Kio",
    "vendors": 38,
    "revenue": 16939.01
  },
  {
    "name": "Geylang Serai Ramadan Bazaar",
    "vendors": 38,
    "revenue": 16891.88
  },
  {
    "name": "Tampines",
    "vendors": 38,
    "revenue": 16800.1
  }
];

export const adminActiveEvents = [
  {
    "id": "1",
    "name": "Toa Payoh Night Market",
    "location": "Toa",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 17618.81
  },
  {
    "id": "2",
    "name": "Jurong East Street Festival",
    "location": "Jurong",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 17527.46
  },
  {
    "id": "3",
    "name": "Clementi Night Bazaar",
    "location": "Clementi",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 17139.62
  }
];

export const adminTopVendors = [
  {
    "name": "Everyday Essentials",
    "revenue": 8240.49
  },
  {
    "name": "Casa Living",
    "revenue": 7869.84
  },
  {
    "name": "Home & More",
    "revenue": 7582.53
  },
  {
    "name": "The Linen Store",
    "revenue": 7073.38
  },
  {
    "name": "Street Fusion",
    "revenue": 4564.32
  },
  {
    "name": "Abang Burger",
    "revenue": 4554.26
  },
  {
    "name": "Mala Majik",
    "revenue": 4545.39
  },
  {
    "name": "Nasi Lemak Bros",
    "revenue": 4513.49
  },
  {
    "name": "Tornado Bites",
    "revenue": 4508.34
  },
  {
    "name": "Cheese Me",
    "revenue": 4500.23
  }
];

export const adminCategoryData = [
  {
    "name": "Hot Food",
    "revenue": 34843.09,
    "transactions": 3101
  },
  {
    "name": "Household Items",
    "revenue": 30766.24,
    "transactions": 1657
  },
  {
    "name": "Trendy Food",
    "revenue": 26451.43,
    "transactions": 2368
  },
  {
    "name": "Desserts",
    "revenue": 14820.4,
    "transactions": 2372
  },
  {
    "name": "Games & Entertainment",
    "revenue": 10912.48,
    "transactions": 1568
  },
  {
    "name": "Drinks",
    "revenue": 10564.76,
    "transactions": 2370
  },
  {
    "name": "Snacks",
    "revenue": 8746.71,
    "transactions": 1564
  }
];

export const adminPaymentData = [
  {
    "name": "Cash",
    "value": 2287
  },
  {
    "name": "QR Code",
    "value": 5210
  },
  {
    "name": "Bazaario Wallet",
    "value": 7503
  }
];

export const adminHourlyData = [
  {
    "hour": "6PM",
    "orders": 758,
    "revenue": 7138.6
  },
  {
    "hour": "7PM",
    "orders": 2322,
    "revenue": 21811.61
  },
  {
    "hour": "8PM",
    "orders": 3635,
    "revenue": 33192.35
  },
  {
    "hour": "9PM",
    "orders": 4467,
    "revenue": 40318.21
  },
  {
    "hour": "10PM",
    "orders": 3087,
    "revenue": 28111.36
  },
  {
    "hour": "11PM",
    "orders": 731,
    "revenue": 6532.98
  }
];

export const adminPerformance = {
  "revenueGrowth": "+15.3%",
  "activeUsers": "500",
  "avgOrderValue": "$9.14",
  "cashlessRate": "84.8%",
  "weekendLift": "44.2%"
};

// ---------------------------------------------------------------------------
// Sentiment Analysis
// ---------------------------------------------------------------------------

export const sentimentByVendor = [
  {
    "vendor": "Sugar Rush",
    "totalReviews": 18,
    "avgRating": 4.0,
    "positivePct": 77.8
  },
  {
    "vendor": "Seoul Kitchen",
    "totalReviews": 19,
    "avgRating": 4.1,
    "positivePct": 73.7
  },
  {
    "vendor": "Kampung Wok",
    "totalReviews": 25,
    "avgRating": 3.6,
    "positivePct": 72.0
  },
  {
    "vendor": "Nasi Lemak Bros",
    "totalReviews": 21,
    "avgRating": 3.7,
    "positivePct": 71.4
  },
  {
    "vendor": "Durian Heaven",
    "totalReviews": 31,
    "avgRating": 3.0,
    "positivePct": 71.0
  },
  {
    "vendor": "Teh Tarik Station",
    "totalReviews": 13,
    "avgRating": 3.3,
    "positivePct": 69.2
  },
  {
    "vendor": "The Satay Corner",
    "totalReviews": 16,
    "avgRating": 3.8,
    "positivePct": 68.8
  },
  {
    "vendor": "Everyday Essentials",
    "totalReviews": 15,
    "avgRating": 3.6,
    "positivePct": 66.7
  },
  {
    "vendor": "Sweet Spot",
    "totalReviews": 21,
    "avgRating": 3.4,
    "positivePct": 66.7
  },
  {
    "vendor": "Mala Majik",
    "totalReviews": 15,
    "avgRating": 3.8,
    "positivePct": 66.7
  },
  {
    "vendor": "Mak Cik Stall",
    "totalReviews": 17,
    "avgRating": 3.4,
    "positivePct": 64.7
  },
  {
    "vendor": "Game On!",
    "totalReviews": 17,
    "avgRating": 3.8,
    "positivePct": 64.7
  },
  {
    "vendor": "Crunch Time",
    "totalReviews": 31,
    "avgRating": 3.4,
    "positivePct": 64.5
  },
  {
    "vendor": "Kacang Queen",
    "totalReviews": 14,
    "avgRating": 2.9,
    "positivePct": 64.3
  },
  {
    "vendor": "Win It Stall",
    "totalReviews": 25,
    "avgRating": 3.2,
    "positivePct": 64.0
  },
  {
    "vendor": "Ice Ice Baby",
    "totalReviews": 24,
    "avgRating": 3.5,
    "positivePct": 62.5
  },
  {
    "vendor": "Boba World",
    "totalReviews": 23,
    "avgRating": 3.1,
    "positivePct": 60.9
  },
  {
    "vendor": "Abang Burger",
    "totalReviews": 29,
    "avgRating": 3.3,
    "positivePct": 58.6
  },
  {
    "vendor": "Cheese Me",
    "totalReviews": 14,
    "avgRating": 2.9,
    "positivePct": 57.1
  },
  {
    "vendor": "Coconut Grove",
    "totalReviews": 23,
    "avgRating": 3.3,
    "positivePct": 56.5
  },
  {
    "vendor": "Kueh Corner",
    "totalReviews": 31,
    "avgRating": 3.2,
    "positivePct": 54.8
  },
  {
    "vendor": "Fun Zone",
    "totalReviews": 31,
    "avgRating": 3.1,
    "positivePct": 54.8
  },
  {
    "vendor": "Ali's Kitchen",
    "totalReviews": 24,
    "avgRating": 3.7,
    "positivePct": 54.2
  },
  {
    "vendor": "The Juice Lab",
    "totalReviews": 13,
    "avgRating": 3.0,
    "positivePct": 53.8
  },
  {
    "vendor": "Uncle Razali Grill",
    "totalReviews": 28,
    "avgRating": 3.1,
    "positivePct": 53.6
  },
  {
    "vendor": "Jelly Bliss",
    "totalReviews": 15,
    "avgRating": 2.7,
    "positivePct": 53.3
  },
  {
    "vendor": "Street Fusion",
    "totalReviews": 17,
    "avgRating": 2.9,
    "positivePct": 52.9
  },
  {
    "vendor": "Snack Attack",
    "totalReviews": 19,
    "avgRating": 3.4,
    "positivePct": 52.6
  },
  {
    "vendor": "Tornado Bites",
    "totalReviews": 21,
    "avgRating": 2.9,
    "positivePct": 52.4
  },
  {
    "vendor": "Home & More",
    "totalReviews": 25,
    "avgRating": 3.4,
    "positivePct": 52.0
  },
  {
    "vendor": "Lucky Strike",
    "totalReviews": 27,
    "avgRating": 3.2,
    "positivePct": 51.9
  },
  {
    "vendor": "Kopi Kaki",
    "totalReviews": 15,
    "avgRating": 3.1,
    "positivePct": 46.7
  },
  {
    "vendor": "Dessert Alley",
    "totalReviews": 22,
    "avgRating": 3.0,
    "positivePct": 45.5
  },
  {
    "vendor": "The Linen Store",
    "totalReviews": 18,
    "avgRating": 2.9,
    "positivePct": 44.4
  },
  {
    "vendor": "Casa Living",
    "totalReviews": 25,
    "avgRating": 3.0,
    "positivePct": 44.0
  },
  {
    "vendor": "K-Food Craze",
    "totalReviews": 23,
    "avgRating": 3.5,
    "positivePct": 43.5
  },
  {
    "vendor": "Munchies Corner",
    "totalReviews": 20,
    "avgRating": 2.6,
    "positivePct": 35.0
  },
  {
    "vendor": "Wok This Way",
    "totalReviews": 15,
    "avgRating": 1.9,
    "positivePct": 26.7
  }
];

export const sentimentSummary = {
  "totalReviews": 800,
  "avgRating": 3.27,
  "positivePct": 57.8,
  "negativePct": 42.2,
  "accuracy": 85.2
};

// ---------------------------------------------------------------------------
// Vendor's Own Reviews (VendorSalesAnalytics.tsx — Reviews tab)
// ---------------------------------------------------------------------------

export const vendorOwnReviews = [
  {
    "id": 14,
    "customer": "Zhi Wei C.",
    "content": "Queue was way too long and the satay was slightly charred. Disappointing.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 8,
    "customer": "Ryan O.",
    "content": "This is my go-to stall every time I visit. Never disappoints with their satay.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 1,
    "customer": "Sarah L.",
    "content": "Amazing chicken satay! Best I've had at a pasar malam. The peanut sauce is incredible.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 12,
    "customer": "Kevin L.",
    "content": "Overpriced for the portion size. Expected more sticks for the price.",
    "rating": 1,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 5,
    "customer": "Jessica W.",
    "content": "Brought my whole family and everyone loved the lamb satay. We ordered two rounds!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 9,
    "customer": "Farah N.",
    "content": "The satay sauce is the real star. Rich, nutty and perfectly balanced. So good!",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 15,
    "customer": "Nurul B.",
    "content": "Satay sauce tasted different today, not as rich. Maybe a bad batch.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 10,
    "customer": "James T.",
    "content": "Tried the mixed platter \u2014 chicken, beef and lamb were all fantastic. 10/10.",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 7,
    "customer": "Mei Ling H.",
    "content": "Incredible quality satay at such affordable prices. The ketupat was fluffy too.",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 11,
    "customer": "Siti A.",
    "content": "Waited 30 minutes for my satay. It was lukewarm by the time I got it.",
    "rating": 1,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 2,
    "customer": "Mike T.",
    "content": "Love the beef satay here. Perfectly grilled and so tender. Will definitely come back!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 6,
    "customer": "David C.",
    "content": "Perfect night out snack. The chicken satay here is always consistent and delicious.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 13,
    "customer": "Rachel G.",
    "content": "The beef satay was a bit tough this time. Not as good as my last visit.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 4,
    "customer": "Ahmad R.",
    "content": "The vendor was so friendly and the satay was fresh off the grill. Highly recommend!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 3,
    "customer": "Priya K.",
    "content": "Great value for money. The mixed satay platter is a must-try for families.",
    "rating": 4,
    "sentiment": "POSITIVE"
  }
];

export const vendorOwnSentiment = {
  "totalReviews": 156,
  "avgRating": 4.3,
  "positivePct": 82.1,
  "negativePct": 17.9
};

// ---------------------------------------------------------------------------
// ML Model Results
// ---------------------------------------------------------------------------

export const mlResults = {
  "revenueForecast": {
    "model": "Linear Regression",
    "task": "Predict vendor daily revenue by day of week",
    "r2Score": 0.873,
    "mae": 6.72
  },
  "demandForecast": {
    "model": "Linear Regression",
    "task": "Predict hourly order volume",
    "r2Score": 0.944,
    "mae": 2.85
  },
  "sentimentAnalysis": {
    "model": "Keyword-based NLP",
    "task": "Classify review sentiment (positive/negative)",
    "accuracy": 85.2
  },
  "cashlessAdoption": {
    "model": "Logistic Regression",
    "task": "Predict cashless payment adoption by category",
    "accuracy": 84.8,
    "topFeatures": [
      "amount",
      "vendor_category_Household Items",
      "vendor_category_Trendy Food"
    ]
  },
  "vendorRevenueForecast": {
    "model": "Linear Regression",
    "task": "Predict total vendor revenue",
    "r2Score": 0.981,
    "mae": 222.78
  }
};

// ---------------------------------------------------------------------------
// Rich Prediction Data
// ---------------------------------------------------------------------------

export const predictions = {
  "vendorForecast": [
    {
      "day": "Mon",
      "predicted": 11.05,
      "actual": 10.25
    },
    {
      "day": "Tue",
      "predicted": 10.8,
      "actual": 9.91
    },
    {
      "day": "Wed",
      "predicted": 10.01,
      "actual": 9.77
    },
    {
      "day": "Thu",
      "predicted": 10.93,
      "actual": 10.48
    },
    {
      "day": "Fri",
      "predicted": 10.51,
      "actual": 10.02
    },
    {
      "day": "Sat",
      "predicted": 14.14,
      "actual": 13.75
    },
    {
      "day": "Sun",
      "predicted": 15.23,
      "actual": 14.59
    }
  ],
  "cashlessByCategory": [
    {
      "category": "Hot Food",
      "currentPct": 85.5,
      "predictedPct": 90.4,
      "transactions": 3101
    },
    {
      "category": "Games & Entertainment",
      "currentPct": 85.1,
      "predictedPct": 91.8,
      "transactions": 1568
    },
    {
      "category": "Desserts",
      "currentPct": 85.0,
      "predictedPct": 89.2,
      "transactions": 2372
    },
    {
      "category": "Drinks",
      "currentPct": 84.9,
      "predictedPct": 89.8,
      "transactions": 2370
    },
    {
      "category": "Snacks",
      "currentPct": 84.6,
      "predictedPct": 90.6,
      "transactions": 1564
    },
    {
      "category": "Household Items",
      "currentPct": 83.9,
      "predictedPct": 89.0,
      "transactions": 1657
    },
    {
      "category": "Trendy Food",
      "currentPct": 83.8,
      "predictedPct": 89.9,
      "transactions": 2368
    }
  ],
  "sentimentTrend": [
    {
      "week": "Week 1",
      "positive": 57.5,
      "negative": 42.5,
      "avgRating": 3.34,
      "reviews": 200,
      "accuracy": 85.5
    },
    {
      "week": "Week 2",
      "positive": 54.5,
      "negative": 45.5,
      "avgRating": 3.36,
      "reviews": 200,
      "accuracy": 87.5
    },
    {
      "week": "Week 3",
      "positive": 63.0,
      "negative": 37.0,
      "avgRating": 3.28,
      "reviews": 200,
      "accuracy": 84.5
    },
    {
      "week": "Week 4",
      "positive": 56.0,
      "negative": 44.0,
      "avgRating": 3.08,
      "reviews": 200,
      "accuracy": 83.5
    }
  ],
  "demandForecast": [
    {
      "hour": "6PM",
      "currentOrders": 8,
      "predictedOrders": 8,
      "revenue": 79.32
    },
    {
      "hour": "7PM",
      "currentOrders": 26,
      "predictedOrders": 28,
      "revenue": 242.35
    },
    {
      "hour": "8PM",
      "currentOrders": 40,
      "predictedOrders": 44,
      "revenue": 368.8
    },
    {
      "hour": "9PM",
      "currentOrders": 50,
      "predictedOrders": 54,
      "revenue": 447.98
    },
    {
      "hour": "10PM",
      "currentOrders": 34,
      "predictedOrders": 36,
      "revenue": 312.35
    },
    {
      "hour": "11PM",
      "currentOrders": 8,
      "predictedOrders": 8,
      "revenue": 72.59
    }
  ],
  "adminVendorForecast": [
    {
      "vendor": "Everyday Essentials",
      "currentRevenue": 8240.49,
      "predictedRevenue": 8938.52,
      "growth": "+17.2%"
    },
    {
      "vendor": "Casa Living",
      "currentRevenue": 7869.84,
      "predictedRevenue": 8926.32,
      "growth": "+12.9%"
    },
    {
      "vendor": "Home & More",
      "currentRevenue": 7582.53,
      "predictedRevenue": 8130.35,
      "growth": "+14.5%"
    },
    {
      "vendor": "The Linen Store",
      "currentRevenue": 7073.38,
      "predictedRevenue": 7577.3,
      "growth": "+9.9%"
    },
    {
      "vendor": "Street Fusion",
      "currentRevenue": 4564.32,
      "predictedRevenue": 5379.68,
      "growth": "+13.3%"
    }
  ]
};
