// ============================================================================
// AUTO-GENERATED by export_to_webapp.py — DO NOT EDIT MANUALLY
// Run: cd bazaario_analytics && python3 export_to_webapp.py
// Generated: 2026-03-28 22:48:50
// ============================================================================

// ---------------------------------------------------------------------------
// Vendor Analytics (VendorSalesAnalytics.tsx)
// ---------------------------------------------------------------------------

export const vendorSalesData = [
  {
    "id": 1,
    "date": "Mon",
    "sales": 1893.71,
    "orders": 187
  },
  {
    "id": 2,
    "date": "Tue",
    "sales": 1934.64,
    "orders": 199
  },
  {
    "id": 3,
    "date": "Wed",
    "sales": 1581.51,
    "orders": 166
  },
  {
    "id": 4,
    "date": "Thu",
    "sales": 2073.45,
    "orders": 196
  },
  {
    "id": 5,
    "date": "Fri",
    "sales": 1873.12,
    "orders": 184
  },
  {
    "id": 6,
    "date": "Sat",
    "sales": 2695.07,
    "orders": 186
  },
  {
    "id": 7,
    "date": "Sun",
    "sales": 2945.13,
    "orders": 204
  }
];

export const vendorProductData = [
  {
    "name": "Lamb Satay (10pc)",
    "value": 4256.45,
    "count": 758
  },
  {
    "name": "Mixed Satay Platter",
    "value": 3906.18,
    "count": 401
  },
  {
    "name": "Chicken Satay (10pc)",
    "value": 3687.88,
    "count": 712
  },
  {
    "name": "Beef Satay (10pc)",
    "value": 2868.17,
    "count": 437
  },
  {
    "name": "Satay Sauce & Ketupat",
    "value": 277.95,
    "count": 34
  }
];

export const vendorHourlyData = [
  {
    "id": 1,
    "hour": "6PM",
    "orders": 61
  },
  {
    "id": 2,
    "hour": "7PM",
    "orders": 201
  },
  {
    "id": 3,
    "hour": "8PM",
    "orders": 325
  },
  {
    "id": 4,
    "hour": "9PM",
    "orders": 396
  },
  {
    "id": 5,
    "hour": "10PM",
    "orders": 275
  },
  {
    "id": 6,
    "hour": "11PM",
    "orders": 64
  }
];

export const vendorStats = [
  {
    "label": "Total Revenue",
    "value": "$14,996.63",
    "change": "+12.5%",
    "positive": true
  },
  {
    "label": "Total Orders",
    "value": "1322",
    "change": "+8.3%",
    "positive": true
  },
  {
    "label": "Avg Order Value",
    "value": "$11.34",
    "change": "-2.1%",
    "positive": false
  },
  {
    "label": "Customers",
    "value": "478",
    "change": "+15.2%",
    "positive": true
  }
];

export const vendorInsights = {
  "revenueGrowth": "+12.5%",
  "weekendLift": "44.1%",
  "totalOrders": 1322,
  "repeatCustomerPct": "68%",
  "avgOrderValue": "$11.34",
  "peakHour": "9:00 PM - 10:00 PM",
  "peakOrders": 396,
  "slowHour": "6:00 PM - 7:00 PM"
};

// ---------------------------------------------------------------------------
// Admin Dashboard (AdminDashboard.tsx)
// ---------------------------------------------------------------------------

export const adminStats = {
  "totalRevenue": 454822.78,
  "totalEvents": 8,
  "totalVendors": 38,
  "activeEvents": 3,
  "totalOrders": 50000,
  "platformFees": 13644.68
};

export const adminRevenueData = [
  {
    "id": 1,
    "date": "Mon",
    "revenue": 59426.35
  },
  {
    "id": 2,
    "date": "Tue",
    "revenue": 58809.23
  },
  {
    "id": 3,
    "date": "Wed",
    "revenue": 53012.79
  },
  {
    "id": 4,
    "date": "Thu",
    "revenue": 58716.08
  },
  {
    "id": 5,
    "date": "Fri",
    "revenue": 57756.05
  },
  {
    "id": 6,
    "date": "Sat",
    "revenue": 82879.87
  },
  {
    "id": 7,
    "date": "Sun",
    "revenue": 84222.41
  }
];

export const adminEventData = [
  {
    "name": "Toa Payoh",
    "vendors": 38,
    "revenue": 57889.14
  },
  {
    "name": "Geylang Serai Ramadan Bazaar",
    "vendors": 38,
    "revenue": 57799.62
  },
  {
    "name": "Jurong East",
    "vendors": 38,
    "revenue": 57355.86
  },
  {
    "name": "Woodlands",
    "vendors": 38,
    "revenue": 57163.26
  },
  {
    "name": "Bedok",
    "vendors": 38,
    "revenue": 56386.83
  },
  {
    "name": "Clementi Bazaar",
    "vendors": 38,
    "revenue": 56344.41
  },
  {
    "name": "Ang Mo Kio",
    "vendors": 38,
    "revenue": 56264.57
  },
  {
    "name": "Tampines",
    "vendors": 38,
    "revenue": 55619.09
  }
];

export const adminActiveEvents = [
  {
    "id": "1",
    "name": "Toa Payoh Night Market",
    "location": "Toa",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 57889.14
  },
  {
    "id": "2",
    "name": "Geylang Serai Ramadan Bazaar",
    "location": "Geylang",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 57799.62
  },
  {
    "id": "3",
    "name": "Jurong East Street Festival",
    "location": "Jurong",
    "vendors": 38,
    "status": "ongoing",
    "revenue": 57355.86
  }
];

export const adminTopVendors = [
  {
    "name": "Everyday Essentials",
    "revenue": 25457.76
  },
  {
    "name": "The Linen Store",
    "revenue": 24616.83
  },
  {
    "name": "Casa Living",
    "revenue": 24608.35
  },
  {
    "name": "Home & More",
    "revenue": 23770.98
  },
  {
    "name": "Cheese Me",
    "revenue": 15109.76
  },
  {
    "name": "The Satay Corner",
    "revenue": 14996.63
  },
  {
    "name": "Tornado Bites",
    "revenue": 14989.19
  },
  {
    "name": "Kampung Wok",
    "revenue": 14864.27
  },
  {
    "name": "Street Fusion",
    "revenue": 14837.85
  },
  {
    "name": "Mala Majik",
    "revenue": 14827.85
  }
];

export const adminCategoryData = [
  {
    "name": "Hot Food",
    "revenue": 116424.33,
    "transactions": 10356
  },
  {
    "name": "Household Items",
    "revenue": 98453.92,
    "transactions": 5264
  },
  {
    "name": "Trendy Food",
    "revenue": 88099.48,
    "transactions": 7835
  },
  {
    "name": "Desserts",
    "revenue": 49064.9,
    "transactions": 7872
  },
  {
    "name": "Games & Entertainment",
    "revenue": 36740.66,
    "transactions": 5352
  },
  {
    "name": "Drinks",
    "revenue": 35615.65,
    "transactions": 7908
  },
  {
    "name": "Snacks",
    "revenue": 30423.84,
    "transactions": 5413
  }
];

export const adminPaymentData = [
  {
    "name": "Cash",
    "value": 7565
  },
  {
    "name": "QR Code",
    "value": 17510
  },
  {
    "name": "Bazaario Wallet",
    "value": 24925
  }
];

export const adminHourlyData = [
  {
    "hour": "6PM",
    "orders": 2469,
    "revenue": 22625.0
  },
  {
    "hour": "7PM",
    "orders": 7663,
    "revenue": 70414.16
  },
  {
    "hour": "8PM",
    "orders": 12347,
    "revenue": 112687.83
  },
  {
    "hour": "9PM",
    "orders": 14932,
    "revenue": 135170.5
  },
  {
    "hour": "10PM",
    "orders": 10085,
    "revenue": 91169.25
  },
  {
    "hour": "11PM",
    "orders": 2504,
    "revenue": 22756.04
  }
];

export const adminPerformance = {
  "revenueGrowth": "+15.3%",
  "activeUsers": "500",
  "avgOrderValue": "$9.10",
  "cashlessRate": "84.9%",
  "weekendLift": "44.3%"
};

// ---------------------------------------------------------------------------
// Sentiment Analysis
// ---------------------------------------------------------------------------

export const sentimentByVendor = [
  {
    "vendor": "Kampung Wok",
    "totalReviews": 17,
    "avgRating": 3.2,
    "positivePct": 76.5
  },
  {
    "vendor": "Cheese Me",
    "totalReviews": 24,
    "avgRating": 4.0,
    "positivePct": 75.0
  },
  {
    "vendor": "Fun Zone",
    "totalReviews": 19,
    "avgRating": 3.4,
    "positivePct": 73.7
  },
  {
    "vendor": "Mak Cik Stall",
    "totalReviews": 18,
    "avgRating": 3.3,
    "positivePct": 72.2
  },
  {
    "vendor": "Tornado Bites",
    "totalReviews": 23,
    "avgRating": 3.6,
    "positivePct": 69.6
  },
  {
    "vendor": "Crunch Time",
    "totalReviews": 23,
    "avgRating": 3.6,
    "positivePct": 69.6
  },
  {
    "vendor": "Seoul Kitchen",
    "totalReviews": 29,
    "avgRating": 3.4,
    "positivePct": 69.0
  },
  {
    "vendor": "Ice Ice Baby",
    "totalReviews": 16,
    "avgRating": 3.6,
    "positivePct": 68.8
  },
  {
    "vendor": "Everyday Essentials",
    "totalReviews": 16,
    "avgRating": 3.6,
    "positivePct": 68.8
  },
  {
    "vendor": "Teh Tarik Station",
    "totalReviews": 24,
    "avgRating": 3.2,
    "positivePct": 66.7
  },
  {
    "vendor": "Kueh Corner",
    "totalReviews": 15,
    "avgRating": 3.9,
    "positivePct": 66.7
  },
  {
    "vendor": "Kacang Queen",
    "totalReviews": 26,
    "avgRating": 3.4,
    "positivePct": 65.4
  },
  {
    "vendor": "Uncle Razali Grill",
    "totalReviews": 26,
    "avgRating": 3.4,
    "positivePct": 65.4
  },
  {
    "vendor": "Ali's Kitchen",
    "totalReviews": 26,
    "avgRating": 4.0,
    "positivePct": 65.4
  },
  {
    "vendor": "Lucky Strike",
    "totalReviews": 23,
    "avgRating": 3.6,
    "positivePct": 65.2
  },
  {
    "vendor": "Game On!",
    "totalReviews": 24,
    "avgRating": 3.1,
    "positivePct": 62.5
  },
  {
    "vendor": "Munchies Corner",
    "totalReviews": 24,
    "avgRating": 2.8,
    "positivePct": 62.5
  },
  {
    "vendor": "The Linen Store",
    "totalReviews": 15,
    "avgRating": 3.5,
    "positivePct": 60.0
  },
  {
    "vendor": "The Satay Corner",
    "totalReviews": 27,
    "avgRating": 3.6,
    "positivePct": 59.3
  },
  {
    "vendor": "Durian Heaven",
    "totalReviews": 24,
    "avgRating": 3.6,
    "positivePct": 58.3
  },
  {
    "vendor": "Casa Living",
    "totalReviews": 19,
    "avgRating": 3.5,
    "positivePct": 57.9
  },
  {
    "vendor": "Wok This Way",
    "totalReviews": 30,
    "avgRating": 3.4,
    "positivePct": 56.7
  },
  {
    "vendor": "Snack Attack",
    "totalReviews": 16,
    "avgRating": 2.9,
    "positivePct": 56.2
  },
  {
    "vendor": "Win It Stall",
    "totalReviews": 25,
    "avgRating": 2.8,
    "positivePct": 56.0
  },
  {
    "vendor": "K-Food Craze",
    "totalReviews": 20,
    "avgRating": 3.2,
    "positivePct": 55.0
  },
  {
    "vendor": "Kopi Kaki",
    "totalReviews": 21,
    "avgRating": 3.0,
    "positivePct": 52.4
  },
  {
    "vendor": "Jelly Bliss",
    "totalReviews": 14,
    "avgRating": 3.4,
    "positivePct": 50.0
  },
  {
    "vendor": "Abang Burger",
    "totalReviews": 10,
    "avgRating": 3.3,
    "positivePct": 50.0
  },
  {
    "vendor": "The Juice Lab",
    "totalReviews": 21,
    "avgRating": 3.0,
    "positivePct": 47.6
  },
  {
    "vendor": "Sugar Rush",
    "totalReviews": 19,
    "avgRating": 3.1,
    "positivePct": 47.4
  },
  {
    "vendor": "Nasi Lemak Bros",
    "totalReviews": 20,
    "avgRating": 3.0,
    "positivePct": 45.0
  },
  {
    "vendor": "Boba World",
    "totalReviews": 29,
    "avgRating": 2.7,
    "positivePct": 44.8
  },
  {
    "vendor": "Mala Majik",
    "totalReviews": 16,
    "avgRating": 2.9,
    "positivePct": 43.8
  },
  {
    "vendor": "Street Fusion",
    "totalReviews": 16,
    "avgRating": 2.6,
    "positivePct": 43.8
  },
  {
    "vendor": "Coconut Grove",
    "totalReviews": 18,
    "avgRating": 3.2,
    "positivePct": 38.9
  },
  {
    "vendor": "Home & More",
    "totalReviews": 24,
    "avgRating": 2.9,
    "positivePct": 37.5
  },
  {
    "vendor": "Dessert Alley",
    "totalReviews": 22,
    "avgRating": 2.3,
    "positivePct": 36.4
  },
  {
    "vendor": "Sweet Spot",
    "totalReviews": 21,
    "avgRating": 2.2,
    "positivePct": 33.3
  }
];

export const sentimentSummary = {
  "totalReviews": 800,
  "avgRating": 3.24,
  "positivePct": 58.0,
  "negativePct": 42.0,
  "accuracy": 83.6
};

// ---------------------------------------------------------------------------
// Vendor's Own Reviews (VendorSalesAnalytics.tsx — Reviews tab)
// ---------------------------------------------------------------------------

export const vendorOwnReviews = [
  {
    "id": 14,
    "customer": "Zhi Wei C.",
    "content": "Queue was way too long and the satay was slightly charred. Disappointing.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 8,
    "customer": "Ryan O.",
    "content": "This is my go-to stall every time I visit. Never disappoints with their satay.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 1,
    "customer": "Sarah L.",
    "content": "Amazing chicken satay! Best I've had at a pasar malam. The peanut sauce is incredible.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 12,
    "customer": "Kevin L.",
    "content": "Overpriced for the portion size. Expected more sticks for the price.",
    "rating": 1,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 5,
    "customer": "Jessica W.",
    "content": "Brought my whole family and everyone loved the lamb satay. We ordered two rounds!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 9,
    "customer": "Farah N.",
    "content": "The satay sauce is the real star. Rich, nutty and perfectly balanced. So good!",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 15,
    "customer": "Nurul B.",
    "content": "Satay sauce tasted different today, not as rich. Maybe a bad batch.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 10,
    "customer": "James T.",
    "content": "Tried the mixed platter \u2014 chicken, beef and lamb were all fantastic. 10/10.",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 7,
    "customer": "Mei Ling H.",
    "content": "Incredible quality satay at such affordable prices. The ketupat was fluffy too.",
    "rating": 5,
    "sentiment": "POSITIVE"
  },
  {
    "id": 11,
    "customer": "Siti A.",
    "content": "Waited 30 minutes for my satay. It was lukewarm by the time I got it.",
    "rating": 1,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 2,
    "customer": "Mike T.",
    "content": "Love the beef satay here. Perfectly grilled and so tender. Will definitely come back!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 6,
    "customer": "David C.",
    "content": "Perfect night out snack. The chicken satay here is always consistent and delicious.",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 13,
    "customer": "Rachel G.",
    "content": "The beef satay was a bit tough this time. Not as good as my last visit.",
    "rating": 2,
    "sentiment": "NEGATIVE"
  },
  {
    "id": 4,
    "customer": "Ahmad R.",
    "content": "The vendor was so friendly and the satay was fresh off the grill. Highly recommend!",
    "rating": 4,
    "sentiment": "POSITIVE"
  },
  {
    "id": 3,
    "customer": "Priya K.",
    "content": "Great value for money. The mixed satay platter is a must-try for families.",
    "rating": 4,
    "sentiment": "POSITIVE"
  }
];

export const vendorOwnSentiment = {
  "totalReviews": 156,
  "avgRating": 4.3,
  "positivePct": 82.1,
  "negativePct": 17.9
};

// ---------------------------------------------------------------------------
// ML Model Results
// ---------------------------------------------------------------------------

export const mlResults = {
  "revenueForecast": {
    "model": "Linear Regression",
    "task": "Predict vendor daily revenue by day of week",
    "r2Score": 0.947,
    "mae": 11.52
  },
  "demandForecast": {
    "model": "Linear Regression",
    "task": "Predict hourly order volume",
    "r2Score": 0.919,
    "mae": 11.4
  },
  "sentimentAnalysis": {
    "model": "Keyword-based NLP",
    "task": "Classify review sentiment (positive/negative)",
    "accuracy": 83.6
  },
  "cashlessAdoption": {
    "model": "Logistic Regression",
    "task": "Predict cashless payment adoption by category",
    "accuracy": 84.9,
    "topFeatures": [
      "amount",
      "hour",
      "vendor_category_Household Items"
    ]
  },
  "vendorRevenueForecast": {
    "model": "Linear Regression",
    "task": "Predict total vendor revenue",
    "r2Score": 0.997,
    "mae": 292.35
  }
};

// ---------------------------------------------------------------------------
// Rich Prediction Data
// ---------------------------------------------------------------------------

export const predictions = {
  "vendorForecast": [
    {
      "day": "Mon",
      "predicted": 457.07,
      "actual": 424.64
    },
    {
      "day": "Tue",
      "predicted": 376.62,
      "actual": 362.75
    },
    {
      "day": "Wed",
      "predicted": 407.85,
      "actual": 397.36
    },
    {
      "day": "Thu",
      "predicted": 446.15,
      "actual": 433.97
    },
    {
      "day": "Fri",
      "predicted": 649.66,
      "actual": 606.68
    },
    {
      "day": "Sat",
      "predicted": 810.19,
      "actual": 771.89
    },
    {
      "day": "Sun",
      "predicted": 689.97,
      "actual": 662.57
    }
  ],
  "cashlessByCategory": [
    {
      "category": "Hot Food",
      "currentPct": 85.4,
      "predictedPct": 90.3,
      "transactions": 10356
    },
    {
      "category": "Desserts",
      "currentPct": 84.9,
      "predictedPct": 91.6,
      "transactions": 7872
    },
    {
      "category": "Household Items",
      "currentPct": 84.9,
      "predictedPct": 89.1,
      "transactions": 5264
    },
    {
      "category": "Snacks",
      "currentPct": 84.9,
      "predictedPct": 89.8,
      "transactions": 5413
    },
    {
      "category": "Drinks",
      "currentPct": 84.7,
      "predictedPct": 90.8,
      "transactions": 7908
    },
    {
      "category": "Trendy Food",
      "currentPct": 84.7,
      "predictedPct": 89.9,
      "transactions": 7835
    },
    {
      "category": "Games & Entertainment",
      "currentPct": 84.5,
      "predictedPct": 90.7,
      "transactions": 5352
    }
  ],
  "sentimentTrend": [
    {
      "week": "Week 1",
      "positive": 57.0,
      "negative": 43.0,
      "avgRating": 3.2,
      "reviews": 200,
      "accuracy": 79.5
    },
    {
      "week": "Week 2",
      "positive": 54.5,
      "negative": 45.5,
      "avgRating": 3.22,
      "reviews": 200,
      "accuracy": 85.0
    },
    {
      "week": "Week 3",
      "positive": 60.0,
      "negative": 40.0,
      "avgRating": 3.18,
      "reviews": 200,
      "accuracy": 84.5
    },
    {
      "week": "Week 4",
      "positive": 60.5,
      "negative": 39.5,
      "avgRating": 3.36,
      "reviews": 200,
      "accuracy": 85.5
    }
  ],
  "demandForecast": [
    {
      "hour": "6PM",
      "currentOrders": 64,
      "predictedOrders": 69,
      "revenue": 555.81
    },
    {
      "hour": "7PM",
      "currentOrders": 175,
      "predictedOrders": 185,
      "revenue": 1665.62
    },
    {
      "hour": "8PM",
      "currentOrders": 340,
      "predictedOrders": 373,
      "revenue": 3018.68
    },
    {
      "hour": "9PM",
      "currentOrders": 420,
      "predictedOrders": 465,
      "revenue": 4663.68
    },
    {
      "hour": "10PM",
      "currentOrders": 274,
      "predictedOrders": 303,
      "revenue": 3074.33
    },
    {
      "hour": "11PM",
      "currentOrders": 95,
      "predictedOrders": 101,
      "revenue": 840.17
    }
  ],
  "adminVendorForecast": [
    {
      "vendor": "Everyday Essentials",
      "currentRevenue": 25457.76,
      "predictedRevenue": 29851.22,
      "growth": "+16.4%"
    },
    {
      "vendor": "The Linen Store",
      "currentRevenue": 24616.83,
      "predictedRevenue": 26854.7,
      "growth": "+13.5%"
    },
    {
      "vendor": "Casa Living",
      "currentRevenue": 24608.35,
      "predictedRevenue": 27104.43,
      "growth": "+16.9%"
    },
    {
      "vendor": "Home & More",
      "currentRevenue": 23770.98,
      "predictedRevenue": 26377.49,
      "growth": "+8.4%"
    },
    {
      "vendor": "Cheese Me",
      "currentRevenue": 15109.76,
      "predictedRevenue": 16349.69,
      "growth": "+12.3%"
    }
  ]
};
